// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdGjpB5pMAa9sv_pWphTLfGT0gEzUP3uc',
    appId: '1:269446033894:web:09b5985fd72b99a931a627',
    messagingSenderId: '269446033894',
    projectId: 'my-first-project-tekmo10',
    authDomain: 'my-first-project-tekmo10.firebaseapp.com',
    storageBucket: 'my-first-project-tekmo10.appspot.com',
    measurementId: 'G-ETGFL842JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMV-fIu8rQ_EHLoHYQAIEOu43MuDQ95q8',
    appId: '1:269446033894:android:abf768e84e746e5e31a627',
    messagingSenderId: '269446033894',
    projectId: 'my-first-project-tekmo10',
    storageBucket: 'my-first-project-tekmo10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMMWMWRHAvG7qqGXH9Aoq45aqRzSqpdGo',
    appId: '1:269446033894:ios:7868ec811cab3b4d31a627',
    messagingSenderId: '269446033894',
    projectId: 'my-first-project-tekmo10',
    storageBucket: 'my-first-project-tekmo10.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Firebase10',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMMWMWRHAvG7qqGXH9Aoq45aqRzSqpdGo',
    appId: '1:269446033894:ios:7868ec811cab3b4d31a627',
    messagingSenderId: '269446033894',
    projectId: 'my-first-project-tekmo10',
    storageBucket: 'my-first-project-tekmo10.appspot.com',
    iosBundleId: 'com.example.flutterApplication1Firebase10',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdGjpB5pMAa9sv_pWphTLfGT0gEzUP3uc',
    appId: '1:269446033894:web:c211ad543184c43531a627',
    messagingSenderId: '269446033894',
    projectId: 'my-first-project-tekmo10',
    authDomain: 'my-first-project-tekmo10.firebaseapp.com',
    storageBucket: 'my-first-project-tekmo10.appspot.com',
    measurementId: 'G-DPLNQ6QRWL',
  );
}
